### ISSUE TITLE
Incorrect types on pattern optional, oneOrMore, zeroOrMore

### ISSUE THREAD

**Issue by milt** [yetanalytics/project-pan#13]
As discussed here: https://github.com/adlnet/xapi-profiles/issues/250

This lib can probably be updated before that, as the intention is clear

**Comment by kelvinqian00** [comment]
Fixed for project-pan in ea035b1f54f7317cc2b302e7ff196b999010f350, though adlnet/xapi-profiles#250 will remain open for now.
